### ISSUE TITLE
Build Fails due to ruby version update

### ISSUE THREAD

**Issue by ShoGinn** [chabad360/htmlproofer#10]
Because ruby needs to be >3.0, the docker build fails, and thus, all actions.

I have already created pull request #9

**Comment by ShoGinn** [comment]
Also, I have changed my fork not to need the docker build and just build the image at every action. See:
https://github.com/ShoGinn/htmlproofer

**Comment by chabad360** [comment]
Alrighty, I'll have a look at the pull request soon (sorry for the delay).

> Also, I have changed my fork not to need the docker build and just build the image at every action.

I do this to reduce the CI time, instead of building on each usage it's just already built. However I do need to migrate to using github packages.
