### ISSUE TITLE
--http_status_ignore=[999,403] doesn't seem to work

### ISSUE THREAD

**Issue by CorruptComputer** [chabad360/htmlproofer#7]
Apologies in advance if this is just me using this wrong.

Linkedin links return status code 999 and some websites will return a 403 with htmlproofer since it uses curl.
Adding `arguments: --http_status_ignore=[999,403]` to the actions yml file seems to successfully ignore that 403 code, but the Linkedin 999 code is not ignored and still shows as an error.

It looks like there was some discussion about this here: https://github.com/gjtorikian/html-proofer/issues/215
But adding that argument doesn't seem to work for the 999 status code when using this Action.

**Comment by CorruptComputer** [comment]
Screenshot of before adding the argument:
![image](https://user-images.githubusercontent.com/5573038/110692703-a1962480-81b4-11eb-8ea2-202cdfea0e76.png)


Screenshot of after adding the argument: (removed the Antergos link between since that site doesn't exist any longer)
![image](https://user-images.githubusercontent.com/5573038/110692663-9642f900-81b4-11eb-8e9a-7c03fba2e4b1.png)

**Comment by chabad360** [comment]
Can you try `--http_status_ignore="999,403"`? This is how it's done in the Readme.

**Comment by CorruptComputer** [comment]
Ah, my bad on that. You are correct, that seems to work. Thanks!
